# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('edge-device', ['core','network'])
    module.source = [
        'model/edge-device.cc',
        'helper/edge-device-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('edge-device')
    module_test.source = [
        'test/edge-device-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'edge-device'
    headers.source = [
        'model/edge-device.h',
        'helper/edge-device-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

